[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"
gas_reports = ["*"]
test = "test"
script = "script"
broadcast = "broadcast"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "solady/=lib/solady/src/",
    "v4-core/=lib/v4-core/src/",
    "v4-core/test/=lib/v4-core/test/",
    "dn404/=lib/dn404/",
    "@uniswap/v3-core/=lib/v3-core/contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/contracts/",
    "@uniswap/v2-core/=lib/v2-core/contracts/"
]

[profile.ci]
fuzz_runs = 1000
invariant_runs = 10000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
